name: "Build Gleam Build Provenance"
description: "Build Gleam Build Provenance"
inputs:
  asset:
    description: "Path to build asset"
    required: true

outputs:
  files:
    description: "Path to all files"
    value: |
      ${{ inputs.asset }}
      ${{ inputs.asset }}.sha256
      ${{ inputs.asset }}.sha512
      ${{ inputs.asset }}.sigstore
      ${{ inputs.asset }}.sbom.spdx.json
      ${{ inputs.asset }}.sbom.cyclonedx.json

runs:
  using: "composite"
  steps:
    - name: Install Cargo SBoM
      shell: bash
      run: cargo install cargo-sbom@~0.9.1

    - name: Generate Build SBoM
      shell: bash
      run: |
        cargo sbom \
          --output-format spdx_json_2_3 \
          > "$ARCHIVE.sbom.spdx.json"
        
        cargo sbom \
          --output-format cyclone_dx_json_1_4 \
          > "$ARCHIVE.sbom.cyclonedx.json"
      env:
        ARCHIVE: "${{ steps.build.outputs.archive }}"

    - name: Hash Build Archive
      shell: bash
      run: |
        openssl dgst -r -sha256 -out "$ARCHIVE".sha256 "$ARCHIVE"
        openssl dgst -r -sha512 -out "$ARCHIVE".sha512 "$ARCHIVE"
      env:
        ARCHIVE: "${{ steps.build.outputs.archive }}"

    - name: Attest Distribution Assets with SBoM
      id: attest-sbom
      uses: actions/attest-sbom@v2
      with:
        subject-path: |
          ${{ steps.build.outputs.archive }}
          ${{ steps.build.outputs.archive }}.sbom.spdx.json
          ${{ steps.build.outputs.archive }}.sbom.cyclonedx.json
        sbom-path: "${{ steps.build.outputs.archive }}.sbom.spdx.json"

    - name: "Copy SBoM provenance"
      id: sbom-provenance
      shell: bash
      run: |
        cp "$ATTESTATION" "$ARCHIVE.sigstore"
      env:
        ARCHIVE: "${{ steps.build.outputs.archive }}"
        ATTESTATION: "${{ steps.attest-sbom.outputs.bundle-path }}"
